In [1]:
import os
import pandas as pd

from portfolio_optimizer.constants import DATA_DIRECTORY, RAW_DATA_DIRECTORY
from portfolio_optimizer.utils.return_metrics import get_returns, get_mean_returns, get_portfolio_return
from portfolio_optimizer.utils.risk_metrics import get_portfolio_std
from portfolio_optimizer.optimization.mean_variance_optimizer import MeanVariancePortfolioOptimizer, mean_variance_optimization

In [2]:
# Read the StockPrices.csv file into a DataFrame called stocks
file_path = os.path.join(RAW_DATA_DIRECTORY, 'StockPrices.csv')
stocks = pd.read_csv(file_path, index_col=0, parse_dates=True)
stocks.head()

/tmp/ipykernel_13981/2196807991.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  stocks = pd.read_csv(file_path, index_col=0, parse_dates=True)


HDFCBANK   HINDUNILVR         IOC    SUNPHARMA  TATAMOTORS
Feb-25  1732.400024  2190.250000  113.489998  1593.250000  620.650024
Jan-25  1698.750000  2468.800049  128.490005  1733.502686  716.099976
Dec-24  1772.849976  2326.850098  136.410004  1875.049683  740.150024
Nov-24  1796.050049  2496.149902  138.630005  1770.231445  786.450012
Oct-24  1735.699951  2518.222656  142.619995  1837.824097  834.049988

In [3]:
stocks.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, Feb-25 to Feb-20
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   HDFCBANK    61 non-null     float64
 1   HINDUNILVR  61 non-null     float64
 2   IOC         61 non-null     float64
 3   SUNPHARMA   61 non-null     float64
 4   TATAMOTORS  61 non-null     float64
dtypes: float64(5)
memory usage: 2.9+ KB


In [4]:
stocks.describe()

HDFCBANK   HINDUNILVR         IOC    SUNPHARMA   TATAMOTORS
count    61.000000    61.000000   61.000000    61.000000    61.000000
mean   1441.388793  2329.406014   82.765374   983.603603   496.174673
std     219.048632   232.979216   42.663505   435.962623   282.850631
min     827.405640  1907.843018   34.885338   335.035889    70.611343
25%    1375.287964  2152.160889   54.110897   642.327576   299.936707
50%    1455.183594  2326.850098   67.738190   916.104858   446.824219
75%    1569.864014  2502.819336  107.265648  1207.769775   642.317871
max    1796.050049  2946.566895  181.669998  1915.157959  1156.650024

In [5]:
# Convert the index to date object
stocks.index = pd.to_datetime(stocks.index, format='%b-%y')

In [6]:
stocks.head()

HDFCBANK   HINDUNILVR         IOC    SUNPHARMA  TATAMOTORS
2025-02-01  1732.400024  2190.250000  113.489998  1593.250000  620.650024
2025-01-01  1698.750000  2468.800049  128.490005  1733.502686  716.099976
2024-12-01  1772.849976  2326.850098  136.410004  1875.049683  740.150024
2024-11-01  1796.050049  2496.149902  138.630005  1770.231445  786.450012
2024-10-01  1735.699951  2518.222656  142.619995  1837.824097  834.049988

In [7]:
# Get the stocks log returns
returns = get_returns(stocks)
returns

HDFCBANK  HINDUNILVR       IOC  SUNPHARMA  TATAMOTORS
2020-03-01 -0.268119    0.056903 -0.189894  -0.055243   -0.449011
2020-04-01  0.162316   -0.045029  0.031231   0.318337    0.312456
2020-05-01 -0.050060   -0.062711 -0.011876   0.021100   -0.067024
2020-06-01  0.120002    0.066847  0.025841  -0.002741    0.129310
2020-07-01 -0.031008    0.018050  0.036321   0.124220    0.065140
2020-08-01  0.080413   -0.041880 -0.029960  -0.019671    0.368371
2020-09-01 -0.033383   -0.023189 -0.138695  -0.038059   -0.069134
2020-10-01  0.097302    0.007958  0.076455  -0.069338   -0.004876
2020-11-01  0.217397    0.032299  0.063482   0.098551    0.359593
2020-12-01 -0.003158    0.120288  0.075059   0.157725    0.019407
2021-01-01 -0.031888   -0.054897  0.025289  -0.010382    0.428882
2021-02-01  0.103488   -0.058240  0.133111   0.023197    0.229349
2021-03-01 -0.026558    0.140452 -0.034005   0.005382   -0.065490
2021-04-01 -0.054464   -0.031976 -0.010887   0.094764   -0.026342
2021-05-01  0.073320   -0.005821  0.202532   0.021163    0.084737
2021-06-01 -0.007565    0.063730 -0.012357   0.010699    0.065412
2021-07-01 -0.047700   -0.055841 -0.044022   0.145829   -0.134423
2021-08-01  0.108626    0.167488  0.090178   0.028674   -0.022623
2021-09-01  0.008568   -0.008186  0.130356   0.030477    0.160285
2021-10-01 -0.007586   -0.108795  0.021149  -0.028414    0.451028
2021-11-01 -0.056417   -0.031590 -0.035767  -0.052076   -0.051892
2021-12-01 -0.009474    0.018382 -0.062631   0.122214    0.051897
2022-01-01  0.004258   -0.036608  0.122870  -0.013243    0.073279
2022-02-01 -0.040015   -0.044706 -0.050161   0.019244   -0.123032
2022-03-01  0.030920   -0.056834  0.034348   0.083955   -0.044709
2022-04-01 -0.058319    0.090889  0.059269   0.015195    0.008876
2022-05-01  0.014805    0.052979 -0.079365  -0.073278    0.013597
2022-06-01 -0.029483   -0.043751 -0.039871  -0.034859   -0.071582
2022-07-01  0.063946    0.182372 -0.017508   0.135565    0.091792
2022-08-01  0.036187    0.008512  0.013680  -0.050061    0.047820
2022-09-01 -0.043570    0.013760 -0.063636   0.062259   -0.141159
2022-10-01  0.053013   -0.054052  0.019417   0.071944    0.020143
2022-11-01  0.074664    0.059458  0.123077   0.028666    0.064567
2022-12-01  0.012248   -0.045933 -0.001957  -0.042684   -0.117091
2023-01-01 -0.015140    0.006130  0.068628   0.033054    0.165356
2023-02-01 -0.002432   -0.045057 -0.069725  -0.068359   -0.069454
2023-03-01  0.006220    0.040518  0.024326   0.027702    0.000238
2023-04-01  0.048492   -0.040248  0.044929   0.004628    0.152448
2023-05-01 -0.034532    0.085561  0.105651  -0.012454    0.085266
2023-06-01  0.056213    0.012173  0.014444   0.078177    0.131579
2023-07-01 -0.029505   -0.043817  0.059057   0.091141    0.085229
2023-08-01 -0.048298   -0.021771 -0.049600  -0.027812   -0.067205
2023-09-01 -0.028731   -0.015748  0.020763   0.042326    0.048586
2023-10-01 -0.032628    0.007463 -0.013744  -0.060458   -0.002460
2023-11-01  0.055740    0.032295  0.309414   0.126079    0.123678
2023-12-01  0.096517    0.046512  0.161969   0.027410    0.104119
2024-01-01 -0.144332   -0.068470  0.131690   0.126246    0.133662
2024-02-01 -0.040443   -0.027906  0.126574   0.118788    0.074644
2024-03-01  0.031709   -0.061331  0.013289   0.026997    0.044833
2024-04-01  0.049865   -0.014971  0.006557  -0.073093    0.015210
2024-05-01  0.021291    0.044206 -0.038200  -0.028161   -0.084235
2024-06-01  0.099409    0.072173  0.019889   0.041821    0.075628
2024-07-01 -0.040415    0.094054  0.142697   0.134104    0.168628
2024-08-01  0.013090    0.026740 -0.025871   0.059499   -0.039165
2024-09-01  0.058128    0.064903  0.017969   0.057667   -0.123004
2024-10-01  0.002107   -0.145371 -0.208326  -0.040380   -0.144257
2024-11-01  0.034770   -0.008765 -0.027976  -0.036779   -0.057071
2024-12-01 -0.012917   -0.067824 -0.016014   0.059212   -0.058872
2025-01-01 -0.041797    0.061005 -0.058060  -0.075490   -0.032493
2025-02-01  0.019809   -0.112828 -0.116741  -0.08090

In [8]:
# Get the mean returns
mean_returns = get_mean_returns(returns)
mean_returns

HDFCBANK      0.009748
HINDUNILVR    0.003499
IOC           0.018411
SUNPHARMA     0.028001
TATAMOTORS    0.037586
dtype: float64

In [9]:
# Get the covariance matrix
cov_matrix = returns.cov()
cov_matrix

HDFCBANK  HINDUNILVR       IOC  SUNPHARMA  TATAMOTORS
HDFCBANK    0.005177    0.000560  0.002237   0.000954    0.005371
HINDUNILVR  0.000560    0.004403  0.001219   0.000665   -0.000680
IOC         0.002237    0.001219  0.007942   0.002581    0.006984
SUNPHARMA   0.000954    0.000665  0.002581   0.005752    0.003387
TATAMOTORS  0.005371   -0.000680  0.006984   0.003387    0.022767

In [10]:
# Get the portfolio return
portfolio_return = get_portfolio_return(mean_returns)
portfolio_return

np.float64(0.019449099291898808)

In [11]:
get_portfolio_std(covariance_matrix=cov_matrix, returns=mean_returns)

array([[0.0608591]])

In [12]:

# # Example usage:
# optimizer = PortfolioOptimizer(mu=mean_returns, cov_matrix=cov_matrix)

# # Minimize volatility with long-only constraint
# weights = optimizer.optimize('min_volatility', ['long_only'], {})

# # Maximize return with required return constraint
# weights = optimizer.optimize('max_return', ['required_return'], {'required_return': 0.03})

# # Minimize volatility with max leverage constraint
# weights = optimizer.optimize('min_volatility', ['max_leverage'], {'max_leverage': 1.5})

In [13]:
best_weights = mean_variance_optimization(mu=mean_returns, cov_matrix=cov_matrix)

In [14]:
best_weights.round(4)*100 # In percentages

array([30.63, 39.75,  3.82, 25.8 ,  0.  ])

In [15]:
# Best Portfolio Return
get_portfolio_return(mean_returns, best_weights)

np.float64(0.01230578801002344)

In [16]:
# Best Portfolio Standard Deviation
get_portfolio_std(covariance_matrix=cov_matrix, returns=mean_returns, weights=best_weights)

array([[0.04625593]])

In [19]:
constraints = ['long_only']
optimizer = MeanVariancePortfolioOptimizer(mu=mean_returns.values, cov_matrix=cov_matrix.values)
objective = 'sharpe_ratio'
params = {'risk_free_rate': 0.05}
weights = optimizer.optimize(objective, constraints, params=params)
weights.round(4)*100 # In percentages

array([ 0.  , -0.  ,  0.  , 45.04, 54.96])

In [20]:
get_portfolio_std(covariance_matrix=cov_matrix, returns=mean_returns, weights=weights)*100

array([[9.85884321]])

In [21]:
get_portfolio_return(mean_returns, weights)*100

np.float64(3.3268470337525042)